Vagrant.configure("2") do |config|
  
    config.vm.box = "debian/bookworm64"
  
    # PC1 connecté au réseau 192.168.56.0 (même réseau que eth1 du routeur)
    config.vm.define "pc1" do |pc1|
      pc1.vm.hostname = "pc1"
      pc1.vm.network "private_network", ip: "192.168.56.20"
    end
  
    # PC2 connecté au réseau privé 192.168.100.0
    config.vm.define "pc2" do |pc2|
      pc2.vm.hostname = "pc2"
      pc2.vm.network "private_network", ip: "192.168.100.20"
    end
  end